以matrix方式监听lava执行结束

diff --git a/.github/workflows/lava-trigger.yml b/.github/workflows/lava-trigger.yml
--- a/.github/workflows/lava-trigger.yml
+++ b/.github/workflows/lava-trigger.yml
@@ -4,7 +4,7 @@ on:
   workflow_call:
     outputs:
       summary_content:
-        value: ${{ jobs.lava-trigger.outputs.summary_content }}
+        value: ${{ jobs.collect-summary.outputs.summary_content }}
 
     inputs:
       kernel_download_url:
@@ -59,7 +59,7 @@ env:
 jobs:
   lava-trigger:
     outputs:
-      summary_content: ${{ steps.summary.outputs.summary_content }}
+      lava_jobid: ${{ steps.run_lava_check.outputs.lava_jobid }}
     runs-on: 'ubuntu-latest'
 
     steps:
@@ -151,53 +151,66 @@ jobs:
           qemu_job_name: ${{ steps.gen_var.outputs.qemu_job_name }}
           testitem_name: ${{ steps.gen_var.outputs.testitem_name }}
         run: |
-          lavacli_admim(){
-              command=$1
-              option=$2
-              if [ "${option}" = "show" ];then
-                option=${option}" --yaml"
-              elif [ ${option} = "wait" ];then
-                option=${option}" --polling 30"
-              fi
-              jobid=$3
-              lavacli --uri https://${lava_admin_token}@${lava_server}/RPC2/ ${command} ${option} ${jobid}
-          }
+          
           set -x
-          lava_jobid=$(lavacli_admim jobs submit ${lava_template})
+          lava_jobid=$(lavacli --uri https://${lava_admin_token}@${lava_server}/RPC2/ jobs submit ${lava_template})
+          echo "lava_jobid=$lava_jobid" >> $GITHUB_OUTPUT
+          seq -s',' 1 40
 
-          for _i in $(seq 1 ${lavacli_max_retry}); do
-              echo " lavacli jobs wait try ${_i} ..."
-              lavacli_admim jobs wait ${lava_jobid} && break
-              if [ ${_i} -lt ${lavacli_max_retry} ]; then
-                  echo "wait ${lavacli_retry_delay} second then retry.."
-                  sleep ${lavacli_retry_delay}
-              else
-                  echo "reach retry maximum number. lavacli jobs wait error!"
-                  exit 1
-              fi
+  lava-result:
+    needs: [lava-trigger]
+    if: ${{ needs.lava-trigger.outputs.lava_jobid }}
+    runs-on: 'ubuntu-latest'
+    strategy:
+      max-parallel: 1
+      matrix:
+        wait: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40]
+    steps:
+      - name: install depends
+        run: |
+          sudo apt-get update
+          sudo apt-get install lavacli
+
+      - name: wait-result ${{ matrix.wait }}
+        env:
+          lava_jobid: ${{ needs.lava-trigger.outputs.lava_jobid }}
+        continue-on-error: true
+        run: |
+          lava_state=$(lavacli --uri https://${lava_admin_token}@${lava_server}/RPC2/ jobs show ${lava_jobid} | grep 'state ' | awk '{print $NF}')
+          while [ "$lava_state" = 'Running' ]; do
+            lavacli --uri https://${lava_admin_token}@${lava_server}/RPC2/ jobs wait --polling $((60 * 60 * 2)) ${lava_jobid} || true
+            lava_state=$(lavacli --uri https://${lava_admin_token}@${lava_server}/RPC2/ jobs show ${lava_jobid} | grep 'state ' | awk '{print $NF}')
+          done
+          
+  
+  collect-summary:
+    outputs:
+      summary_content: ${{ steps.summary.outputs.summary_content }}
+    runs-on: 'ubuntu-latest'
+    needs: [lava-trigger, lava-result]
+    if: ${{ !cancelled() }}
+    env: 
+      lava_jobid: ${{ needs.lava-trigger.outputs.lava_jobid }}
+    steps:
+      - id: summary
+        run: |
+          lava_health=$(lavacli --uri https://${lava_admin_token}@${lava_server}/RPC2/ jobs show ${lava_jobid} | grep 'Health ' | awk '{print $NF}')
+          lava_results=$(lavacli --uri https://${lava_admin_token}@${lava_server}/RPC2/ results ${lava_jobid} | sed '1d')
+          
+          declare -A cnt_result_status=()
+          while read -r st; do
+            cnt_result_status[$st]=$((cnt_result_status[$st] + 1))
+          done < <(awk '{print $NF}' <<< "$lava_results")
+
+          result_status_desc=""
+          for st in "${!cnt_result_status[@]}"; do
+            result_status_desc+="${result_status_desc:+, }$st: ${cnt_result_status[$st]}"
           done
 
-          sleep 5
-          echo "lava_log=https://lava.oerv.ac.cn/scheduler/job/${lava_jobid}" >> $GITHUB_OUTPUT
-          lava_result=$(lavacli_admim jobs show ${lava_jobid} | yq .health)
-          echo "lava_result=$lava_result" >> $GITHUB_OUTPUT
-          if [ "${lava_result}" != '"Complete"' ];then
-            exit 1
-          fi
-          
-
-
-      
-      - name: summary
-        id: summary
-        if: ${{ !cancelled() }}
-        env:
-          lava_log: ${{ steps.run_lava_check.outputs.lava_log }}
-          lava_result: ${{ steps.run_lava_check.outputs.lava_result }}
-        run: |
-          
           cat > summary << EEE
           ## LAVA Check
+          
+          ### args:
           
           - testcase_repo: ${testcase_repo}
           - testcase_ref: ${testcase_ref}
@@ -206,23 +219,24 @@ jobs:
           - kernel_download_url: ${kernel_download_url}
           - rootfs_download_url: ${rootfs_download_url}
           
-          lava log: ${lava_log}
+          ### result:
+          
+          $(if [ "${lava_health}" = Complete ]; then echo "Lava check done!"; else echo "Lava check fail!"; fi) lava log: https://${lava_server}/scheduler/job/${lava_jobid}
 
-          $(if [ "${lava_result}" = '"Complete"' ]; then echo "Lava check done!"; else echo "Lava check fail!"; fi) result url: ${lava_result_url}
+          lava result count: $result_status_desc
 
           EEE
 
-          
           echo "summary_content<<EOF" >> $GITHUB_OUTPUT
           cat summary >> $GITHUB_OUTPUT
           echo "EOF" >> $GITHUB_OUTPUT
           
           cat > $GITHUB_STEP_SUMMARY << EEE
           $(cat summary)
-
-          ### setupd template:
           
-          \`\`\`yaml
-          $(cat "${lava_template}")
+          ### detail result:
+
+          \`\`\`log
+          $lava_results
           \`\`\`
           EEE
